# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: df74fd60304ebe898e422652a738ef6b015751aacc8e9c3153f505fb4ffbc96a9c9de8a06480233796341a2080e02aa475ca510b78d13a62ce6a17d0a23a4b00

test:
  secret_key_base: 2848dc60c5e376bcc54392e117c64b9cc7cd7db2e6a0efc7929762ef429985dc7d6f60f729bb9aecbeebf480aa8dc949250ce9df307db8214179cdc754397e77

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
